Setup and Update: add ability to run specific script Usage: ./bin/breedbase setup 5, ./bin/breedbase update 4 will run the setup or update script that starts with the specified argument

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -7,6 +7,12 @@
 #
 
 
+# Script that is specified to run
+# skip the docker pulls
+# force running the specified script
+SCRIPT=""
+
+
 # Get BB Home Directory
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
@@ -30,28 +36,51 @@ BREEDBASE="$BB_HOME/bin/breedbase"
 SETUP_SCRIPTS="$BB_HOME/bin/setup.d/"
 
 
+# Parse the arguments for a specific script
+if [[ ! -z "$1" ]]; then
+    files=$(find "$SETUP_SCRIPTS" -name "$1*")
+    count=$(echo -n "$files" | grep -c '^')
+    if [[ $count -eq 0 ]]; then
+        echo "ERROR: no matching script found!"
+        exit 1
+    elif [[ $count -gt 1 ]]; then
+        echo "ERROR: multiple matching scripts found!"
+        exit 1
+    else
+        SCRIPT=$(basename "$files")
+    fi
+fi
+
+
 echo "======== T3/BREEDBASE INITIAL SETUP ========"
 
 
 #
 # DOWNLOAD DOCKER IMAGES
 #
-echo ""
-echo "==> Downloading T3/Breedbase Database Image..."
-db_update=$("$DOCKER" pull "$BB_DB_REPO")
-db_update_status=$(echo "$db_update" | grep ^Status)
-echo "$db_update_status"
+if [ -z "$SCRIPT" ]; then
+    echo ""
+    echo "==> Downloading T3/Breedbase Database Image..."
+    db_update=$("$DOCKER" pull "$BB_DB_REPO")
+    db_update_status=$(echo "$db_update" | grep ^Status)
+    echo "$db_update_status"
 
-echo "==> Downloading T3/Breedbase Web Image..."
-web_update=$("$DOCKER" pull "$BB_WEB_REPO")
-web_update_status=$(echo "$web_update" | grep ^Status)
-echo "$web_update_status"
+    echo "==> Downloading T3/Breedbase Web Image..."
+    web_update=$("$DOCKER" pull "$BB_WEB_REPO")
+    web_update_status=$(echo "$web_update" | grep ^Status)
+    echo "$web_update_status"
+fi
 
 
 #
 # RUN SETUP SCRIPTS
 #
-for f in "$SETUP_SCRIPTS/"*.sh; do
+if [ -z "$SCRIPT" ]; then
+    scripts="*.sh"
+else
+    scripts="$SCRIPT"
+fi
+for f in "$SETUP_SCRIPTS"/$scripts; do
     echo ""
     echo "[$(basename $f)]"
     if ! bash "$f" "$BB_HOME"; then 
@@ -64,14 +93,16 @@ done
 #
 # DISPLAY BASIC HELP INFO
 # 
-echo ""
-echo "======== INTIAL T3/BREEDBASE SETUP COMPLETE ========"
-echo "To start/stop the services use the 'breedbase' script located at:"
-echo "$BREEDBASE"
-echo "Examples:"
-echo "breedbase start - starts all services (database and all web instances)"
-echo "breedbase start db triticum - starts specified services (database and wheat instance)"
-echo "breedbase stop - stops all services"
-echo "breedbase stop triticum - stops the specified services (wheat instance)"
-echo ""
-echo "Refer to the README.md document for more information on configuration options."
+if [ -z "$SCRIPT" ]; then
+    echo ""
+    echo "======== INTIAL T3/BREEDBASE SETUP COMPLETE ========"
+    echo "To start/stop the services use the 'breedbase' script located at:"
+    echo "$BREEDBASE"
+    echo "Examples:"
+    echo "breedbase start - starts all services (database and all web instances)"
+    echo "breedbase start db triticum - starts specified services (database and wheat instance)"
+    echo "breedbase stop - stops all services"
+    echo "breedbase stop triticum - stops the specified services (wheat instance)"
+    echo ""
+    echo "Refer to the README.md document for more information on configuration options."
+fi
diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -20,17 +20,16 @@
 # skip the docker pulls
 # force running the update scripts
 SETUP=0
-if [[ "$1" == "--setup" ]]; then
-    SETUP=1
-fi
 
 # Flag for forcing the update scripts to run
 # perform the docker pulls
 # force running the update scripts
 FORCE=0
-if [[ "$1" == "--force" ]]; then
-    FORCE=1
-fi
+
+# Script that is specified to run
+# skip the docker pulls
+# force running the specified script
+SCRIPT=""
 
 
 # Get BB Home Directory
@@ -60,8 +59,30 @@ BB_WEB_REPO="triticeaetoolbox/breedbase_web"
 EXIT_CODE=0
 
 
+# Parse the first argument for the flags or script to run
+if [[ "$1" == "--setup" ]]; then
+    SETUP=1
+elif [[ "$1" == "--force" ]]; then
+    FORCE=1
+elif [[ ! -z "$1" ]]; then
+    files=$(find "$UPDATE_SCRIPTS" -name "$1*")
+    count=$(echo -n "$files" | grep -c '^')
+    if [[ $count -eq 0 ]]; then
+        echo "ERROR: no matching script found!"
+        exit 1
+    elif [[ $count -gt 1 ]]; then
+        echo "ERROR: multiple matching scripts found!"
+        exit 1
+    else
+        SCRIPT=$(basename "$files")
+    fi
+fi
+
+
+
 echo "======== T3/BREEDBASE UPDATE SCRIPT ========"
 echo ""
+
 
 
 #
@@ -69,7 +90,7 @@ echo ""
 #
 
 # Skip if coming from the setup script...
-if [ "$SETUP" -ne 1 ]; then
+if [ "$SETUP" -ne 1 ] && [ -z "$SCRIPT" ]; then
 
     # Update the Database Image
     echo "==> Updating T3/Breedbase Database Image..."
@@ -108,11 +129,17 @@ fi
 #
 # RUN UPDATE SCRIPTS
 #
-if [[ ("$db_updated" -eq 1) || ("$web_updated" -eq 1) || ("$SETUP" -eq 1) || ("$FORCE" -eq 1) ]]; then
+if [[ ("$db_updated" -eq 1) || ("$web_updated" -eq 1) || ("$SETUP" -eq 1) || ("$FORCE" -eq 1) || (! -z "$SCRIPT") ]]; then
     echo ""
     echo "==> Running update scripts..."
+
+    if [ -z "$SCRIPT" ]; then
+        scripts="*.sh"
+    else
+        scripts="$SCRIPT"
+    fi
     
-    for f in "$UPDATE_SCRIPTS/"*.sh; do
+    for f in "$UPDATE_SCRIPTS"/$scripts; do
         echo ""
         echo "[$(basename $f)]"
         if ! bash "$f" "$BB_HOME"; then 
